In [1]:
from mxnet import nd

In [2]:
'''
    1. Getting Started
'''
# Create a vector with 12 consecutive integers
x = nd.arange(12)
print(x)
print(x.shape)
print(x.size)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>
(12,)
12


In [5]:
# Use the reshape function to change the shape of one array that contains the same number of elements
x = x.reshape(3, 4)
print(x)

# NDArray can automatically work out one dimension given the other using -1
x = x.reshape(4, -1)
print(x)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<NDArray 4x3 @cpu(0)>


In [18]:
#The empty method just grabs some memory and hands us back a matrix without setting the values of any of its entries
print("Empty: ", nd.empty((3, 4)))

print("Zeros: ", nd.zeros((3, 4)))

print("Ones: ", nd.ones((3, 4)))

y = nd.array([[1,2,3,4], [4,3,2,1]])
print("Specify the value of each element: ", y)

# Sampled in a normal distribution with zero mean and unit variance
print("Normal distribution: ", nd.random.normal(0, 1, shape=(3, 4)))


Empty:  
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>
Zeros:  
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>
Ones:  
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>
Specify the value of each element:  
[[1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 2x4 @cpu(0)>
Normal distribution:  
[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>


In [23]:
'''
    2. Operations
'''
# Element-wise operations
x = nd.array([1, 2, 4, 8])
y = nd.ones_like(x) * 2

print('x =', x)
print('y =', y)
print('x + y', x + y)
print('x - y', x - y)
print('x * y', x * y)
print('x / y', x / y)

print("Exponentiation: ", x.exp())


x = 
[1. 2. 4. 8.]
<NDArray 4 @cpu(0)>
y = 
[2. 2. 2. 2.]
<NDArray 4 @cpu(0)>
x + y 
[ 3.  4.  6. 10.]
<NDArray 4 @cpu(0)>
x - y 
[-1.  0.  2.  6.]
<NDArray 4 @cpu(0)>
x * y 
[ 2.  4.  8. 16.]
<NDArray 4 @cpu(0)>
x / y 
[0.5 1.  2.  4. ]
<NDArray 4 @cpu(0)>
Exponentiation:  
[2.7182817e+00 7.3890562e+00 5.4598148e+01 2.9809580e+03]
<NDArray 4 @cpu(0)>


In [42]:
# Inner product of 2 matrices
x = nd.arange(12).reshape((3, 4))
y = nd.array([[2, 1, 3, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
print("nd.dot: ", nd.dot(x, y.T))

# Merge 2 matrices
print("Concat dim0:", nd.concat(x, y, dim = 0))
print("Concat dim1:", nd.concat(x, y, dim = 1))

# Support logical statements
print("Equal: ", x == y)
print("Larger than: ", x > y)

# Sum over all elements
print("Sum:", x.sum())

# Transform the result into a scalar in python using hte asscalar function
print("asscalar: ", x.norm().asscalar())

nd.dot:  
[[ 19.  20.  10.]
 [ 59.  60.  50.]
 [ 99. 100.  90.]]
<NDArray 3x3 @cpu(0)>
Concat dim0: 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  3.  4.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>
Concat dim1: 
[[ 0.  1.  2.  3.  2.  1.  3.  4.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>
Equal:  
[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>
Larger than:  
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>
Sum: 
[66.]
<NDArray 1 @cpu(0)>
asscalar:  22.494442


In [35]:
'''
    3. Broadcast Mechanism
'''
# If 2 matrices shape are different from each other. Analogous to numpy:
# Copy the elements appropriately so that 2 NDArrays have the same shape, and then carry out operations by element.
a = nd.arange(3).reshape((3, 1))
b = nd.arange(2).reshape((1, 2))
print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)

a =  
[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>
b =  
[[0. 1.]]
<NDArray 1x2 @cpu(0)>
a + b =  
[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>


In [41]:
'''
    4. Indexing and Slicing
'''
x = nd.arange(12).reshape((3, 4))
print("x[1:3]", x[1:3])
print("x[1,2]", x[1,2])

x[0:2, :] = 12
print("x = ", x)

x[1:3] 
[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>
x[1,2] 
[6.]
<NDArray 1 @cpu(0)>
x =  
[[12. 12. 12. 12.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


In [44]:
'''
    5. Saving Memory
'''
# Python's id() function, which gives us the exact address of the referenced object in memory
before = id(y)
y = x + y
id(y) == before

False

In [46]:
# Performing in-place operations in MXNet is easy, but it still allocate a temporary buffer
z = y.zeros_like()
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))


id(z): 4716330848
id(z): 4716330400


In [47]:
# To avoid temporary buffer, directly invoke the underlying ndarray operation
before = id(z)
nd.elemwise_add(x, y, out=z)
id(z) == before

True

In [49]:
#If the value of x is not reused in subsequent computations, we can also use x[:] = x + y or x += y to reduce the memory overhead of the operation.
before = id(x)
x += y
id(x) == before


True

In [50]:
'''
     6. Mutual Transformation of NDArray and NumPy
'''
# The converted arrays do not share memory
a = x.asnumpy()
print(type(a))
b = nd.array(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>
